FROM ubuntu:24.04

# This is akraradet convention.
ARG WORKDIR=/Projects/Python-for-Machine-Learning
WORKDIR ${WORKDIR}
# Ubuntu already have `ubuntu` user
ARG USERNAME=ubuntu
ARG USER_UID=1000
ARG USER_GID=$USER_UID

# Create the user
# RUN groupadd --gid $USER_GID $USERNAME \
#     && useradd --uid $USER_UID --gid $USER_GID -m $USERNAME
#
# [Optional] Add sudo support. Omit if you don't need to install software after connecting.
RUN apt-get update \
&& apt-get install -y sudo \
&& echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
&& chmod 0440 /etc/sudoers.d/$USERNAME

# Python 
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

RUN apt install -y --no-install-recommends vim

RUN apt clean
RUN rm -rf /var/lib/apt/lists/*

# uv setup 
COPY --from=ghcr.io/astral-sh/uv:0.8.11 /uv /uvx /bin/
# Enable bytecode compilation
ENV UV_COMPILE_BYTECODE=1
# Copy from the cache instead of linking since it's a mounted volume
ENV UV_LINK_MODE=copy
# UV will instapp python in the ~/.local/uv/python by default which won't be cached when container is destroyed.
# Change the path to project folder so it easier to cache.
ENV UV_PYTHON_INSTALL_DIR=${WORKDIR}/.python
# Add uv tools path
ENV PATH="/home/${USERNAME}/.local/bin:$PATH"
# Place executables in the environment at the front of the path
ENV PATH="${WORKDIR}/.venv/bin:$PATH"

# COPY start script with USERNAME privilege
COPY --chown=${USER_UID}:${USER_GID} start.sh /start.sh

# [Optional] Set the default user. Omit if you want to keep the default as root.
USER $USERNAME
WORKDIR ${WORKDIR}
# # Install the project's dependencies using the lockfile and settings
# RUN --mount=type=bind,source=uv.lock,target=uv.lock \
#     --mount=type=bind,source=pyproject.toml,target=pyproject.toml \
#     uv sync --locked --no-install-project --no-dev
# COPY ./data data
# COPY ./src  src
# COPY ./README.md README.md
# Reset the entrypoint, don't invoke `uv`
ENTRYPOINT []
CMD ["sleep", "infinity"]
# CMD [ "uv", "run", "uvicorn", "src:app", "--host=0.0.0.0", "--port=8000", "--workers=2"]